version: '2.0'

services:
  influxdb:
    #2.0 need user/password
    image: influxdb:1.8
    networks:
      - app-dev
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    networks:
      - app-dev
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./docker/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6:
    image: loadimpact/k6:latest
    networks:
      - app-dev
    ports:
      - "6565:6565"
    env_file: .env
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
      # - K6_INFLUXDB_USERNAME=admin
      # - K6_INFLUXDB_PASSWORD=T4l3nt
    #command: "run /scripts/start.js"
    volumes:
      - ./scripts:/scripts

networks:
  app-dev:
    external: true